Vagrant.configure("2") do |config| 
    config.vm.box = "jacobw/fedora35-arm64" 

    
    config.vm.network "private_network", ip: "192.168.56.12"
    config.vm.provider "vmware_desktop" do |vmware|
      vmware.gui = true
      vmware.allowlist_verified = true
    end


  end


  config.vm.define "server" do |server|
    server.vm.hostname = "server"
    server.vm.network "private_network", type: "dhcp"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

  # Client VM configuration
  config.vm.define "client" do |client|
    client.vm.hostname = "client"
    client.vm.network "private_network", type: "dhcp"
    client.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end
  end