# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stock_trading.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13stock_trading.proto\x12\x0cstocktrading\"#\n\rLookupRequest\x12\x12\n\nstock_name\x18\x01 \x01(\t\"/\n\x0eLookupResponse\x12\r\n\x05price\x18\x01 \x01(\x01\x12\x0e\n\x06volume\x18\x02 \x01(\x05\"B\n\x0cTradeRequest\x12\x12\n\nstock_name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x0c\n\x04type\x18\x03 \x01(\t\"\x1f\n\rTradeResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\"2\n\rUpdateRequest\x12\x12\n\nstock_name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\" \n\x0eUpdateResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x32\xda\x01\n\x0cStockTrading\x12\x43\n\x06Lookup\x12\x1b.stocktrading.LookupRequest\x1a\x1c.stocktrading.LookupResponse\x12@\n\x05Trade\x12\x1a.stocktrading.TradeRequest\x1a\x1b.stocktrading.TradeResponse\x12\x43\n\x06Update\x12\x1b.stocktrading.UpdateRequest\x1a\x1c.stocktrading.UpdateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stock_trading_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOOKUPREQUEST']._serialized_start=37
  _globals['_LOOKUPREQUEST']._serialized_end=72
  _globals['_LOOKUPRESPONSE']._serialized_start=74
  _globals['_LOOKUPRESPONSE']._serialized_end=121
  _globals['_TRADEREQUEST']._serialized_start=123
  _globals['_TRADEREQUEST']._serialized_end=189
  _globals['_TRADERESPONSE']._serialized_start=191
  _globals['_TRADERESPONSE']._serialized_end=222
  _globals['_UPDATEREQUEST']._serialized_start=224
  _globals['_UPDATEREQUEST']._serialized_end=274
  _globals['_UPDATERESPONSE']._serialized_start=276
  _globals['_UPDATERESPONSE']._serialized_end=308
  _globals['_STOCKTRADING']._serialized_start=311
  _globals['_STOCKTRADING']._serialized_end=529
# @@protoc_insertion_point(module_scope)
